version: 0.2

env:
  variables:
    NODE_ENV: "production"
    DeployBucket: "comovotar2021.com"
    CloudFrontDistribution: "E219FQ5MMFKW4C"

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install -g gatsby

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - gatsby build

  post_build:
    commands:
      # copy the contents of /public to S3  | Use ${DeployBucket} with CloudFormation
      - aws s3 cp --recursive --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./public s3://comovotar2021.com/ 

      # invalidate the CloudFront cache for /public | Use ${CloudFrontDistribution} with CloudFormation
      - >
        aws cloudfront create-invalidation --distribution-id E219FQ5MMFKW4C 
        --paths /*

cache:
  paths:
    - './node_modules/**/*'
    - './.cache/**/*'
    - './.wordpress-cache/**/*'
    - './WordPress/**/*'

artifacts:
  files:
    - '**/*'
  base-directory: public